### ISSUE TITLE
Markbot is not satisfied with my contrast

### ISSUE THREAD

**Issue by Thebeerz** [Thebeerz/kraken-good-accessibility#1]
I added a background colour for the header, disabled images and thought the contrast was fine. I'm not too sure what the problem is. Thank you! :) 

![Screen Shot 2020-09-28 at 2 51 34 PM](https://user-images.githubusercontent.com/55193140/94473542-4c340100-019a-11eb-9d69-05b434dce622.png)

@mackenzierose

**Comment by MacKenzieRose** [comment]
It looks like Markbot wants a darker green background to contrast with the white text: try `#1e7c74` and let me know how that goes 😄

**Comment by Thebeerz** [comment]
It worked! thank you!! 😄
